baseurl: 'https://martinovic.blog/'
defaultContentLanguage: en-gb
theme: izi
enableRobotsTXT: true
PygmentsCodeFences: true
PygmentsStyle: monokailight

params:
  author: Antonio Martinović
  bio: >-
    I'm a team lead and tech enthusiast, this is my place for writing about things I find interesting including,
    development, tech and leadership. I also enjoy asking the stupid questions and giving unsolicited advice.
  description: Blog by Antonio Martinović

  avatar: images/avatar.png

  enableRSS: true
  hiddenPostSummaryInHomePage: true

  titleFont: 'https://fonts.googleapis.com/css?family=Unna'
  textFont: 'https://fonts.googleapis.com/css?family=Open+Sans'

  customCSS:
    - css/theme.css

  customJS: []

social:
  email: 'mailto:antonio.martinovic@pm.me'
  github: 'https://www.github.com/TopHatCroat'
  linkedin: 'https://www.linkedin.com/in/antonio-martinovi%C4%87-29203210a/'
  stackoverflow: 'https://stackoverflow.com/users/4828716/antonio-martinovi%c4%87'
  mastodon: 'https://mastodon.social/@sike'
