baseurl: 'https://martinovic.blog/'
themesDir: ./themes
languageCode: en-gb
defaultContentLanguage: en-gb
theme: mini
googleAnalytics: UA-127132219-1
enableRobotsTXT: true
PygmentsCodeFences: true
PygmentsStyle: monokailight

params:
  author: Antonio Martinović
  bio: >-
    I'm a team lead and tech enthusiast, this is my place for writing about things I find interesting including,
    development, tech and leadership. I also enjoy listening to jazz while philosophizing about great life questions.

  avatarImage: images/avatar.png

  enableRSS: true
  hiddenPostSummaryInHomePage: true

  titleFont: 'https://fonts.googleapis.com/css?family=Unna'
  textFont: 'https://fonts.googleapis.com/css?family=Open+Sans'

  customCSS:
    - css/theme.css
  customJS: []

  home: ''
  subscribe: ''
  olderPosts: ''
  newerPosts: ''
  readMore: ''
  copyright: ''
  aboutAuthor: I'm an eager full stack developer
  tweet: ''
  share: ''
  title404: ''
  subtitle404: ''

social:
  email: 'mailto:antonio.martinovic@pm.me'
  github: 'https://www.github.com/TopHatCroat'
  linkedin: 'https://www.linkedin.com/in/antonio-martinovi%C4%87-29203210a/'
  stackoverflow: 'https://stackoverflow.com/users/4828716/antonio-martinovi%c4%87'
  mastodon: 'https://mastodon.social/@sike'
