baseurl: 'https://martinovic.blog/'
defaultContentLanguage: en-gb
theme: izi
enableRobotsTXT: true
PygmentsCodeFences: true
PygmentsStyle: monokailight
googleAnalytics: G-9KTDTQ6HHZ

title: Antonio Martinović blog

author:
  name: Antonio Martinović
  email: martinovic.antonio@gmail.com

copyright: 'Copyright'

markup:
  highlight:
    # but you can also be speciffic by specifying the language when opening the blog, for example: ```java
    guessSyntax: true
    # makes it use CSS clases so colours can be adapted with CSS, for example for dark themes
    noClasses: false

params:
  bio: >-
    I'm a team lead and tech enthusiast, this is my place for writing about things I find interesting including,
    development, tech and leadership. I also enjoy asking the stupid questions and giving unsolicited advice.
  description: Blog by Antonio Martinović

  editUrl: https://github.com/tophatcroat/blog/tree/master

  avatar: images/avatar.png

  enableRSS: true
  hiddenPostSummaryInHomePage: true

  titleFont: 'https://fonts.googleapis.com/css?family=Unna'
  textFont: 'https://fonts.googleapis.com/css?family=Open+Sans'

  customCSS:
    - css/theme.css

  customJS: []

social:
  email: 'mailto:antonio.martinovic@pm.me'
  github: 'https://www.github.com/TopHatCroat'
  linkedin: 'https://www.linkedin.com/in/antonio-martinovi%C4%87-29203210a/'
  stackoverflow: 'https://stackoverflow.com/users/4828716/antonio-martinovi%c4%87'
  mastodon: 'https://mastodon.social/@sike'
